/**
 * generated by Xtext 2.31.0
 */
package org.example.domainmodel.tests;

import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.example.domainmodel.domainmodel.AbstractElement;
import org.example.domainmodel.domainmodel.Domainmodel;
import org.example.domainmodel.domainmodel.DomainmodelPackage;
import org.example.domainmodel.domainmodel.Entity;
import org.example.domainmodel.domainmodel.Feature;
import org.example.domainmodel.validation.DomainmodelValidator;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(DomainmodelInjectorProvider.class)
@SuppressWarnings("all")
public class DomainmodelParsingTest {
  @Inject
  private ParseHelper<Domainmodel> parseHelper;

  @Inject
  private ValidationTestHelper validationTestHelper;

  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final Domainmodel result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void parseDomainmodel() {
    try {
      final Domainmodel model = this.parseHelper.parse(
        "entity MyEntity {\r\n                 parent: MyEntity\r\n             }");
      AbstractElement _head = IterableExtensions.<AbstractElement>head(model.getElements());
      final Entity entity = ((Entity) _head);
      Assertions.assertSame(entity, IterableExtensions.<Feature>head(entity.getFeatures()).getType());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void testValidModel() {
    try {
      final Domainmodel entity = this.parseHelper.parse(
        "entity MyEntity {\r\n\t             parent: MyEntity\r\n\t         }");
      this.validationTestHelper.assertNoIssues(entity);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void testNameStartsWithCapitalWarning() {
    try {
      final Domainmodel entity = this.parseHelper.parse(
        "entity myEntity {\r\n\t             parent: myEntity\r\n\t         }");
      this.validationTestHelper.assertWarning(entity, 
        DomainmodelPackage.Literals.ENTITY, 
        DomainmodelValidator.INVALID_NAME, 
        "Name should start with a capital");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
